application: marry-fuck-kill-hrd
version: staging
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: resources/favicon.ico
  upload: resources/favicon.ico

- url: /robots.txt
  static_files: resources/robots.txt
  upload: resources/robots.txt

- url: /s
  static_dir: static

- url: /admin/.*
  script: admin.application
  login: admin

- url: /.*
  script: main.application

error_handlers:
- error_code: over_quota
  file: over_quota.html

builtins:
- remote_api: on

includes:
- mapreduce/include.yaml
