application: marry-fuck-kill
version: 1
runtime: python
api_version: 1

handlers:
- url: /debug(/.+)?
  script: main.py

- url: /make
  static_files: gwt-war/MfkMaker.html
  upload: gwt-war/.*

- url: /
  static_files: gwt-war/MfkWeb.html
  upload: gwt-war/.*

- url: /
  static_dir: gwt-war



