application: marry-fuck-kill
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /s
  static_dir: static

- url: /.*
  script: main.py

