application: marry-fuck-kill
version: 1
runtime: python
api_version: 1

handlers:
- url: /debug(/.+)?
  script: debug.py
  login: admin

- url: /(rpc|i)/.*
  script: main.py

- url: /make
  static_files: gwt-war/MfkMaker.html
  upload: gwt-war/.*

- url: /vote(/.*)?
  static_files: gwt-war/MfkWeb.html
  upload: gwt-war/.*

- url: /about
  static_files: gwt-war/about.html
  upload: gwt-war/.*

# The root page is an alias for /vote.
- url: /
  static_files: gwt-war/MfkWeb.html
  upload: gwt-war/.*

# These are all other files under root.
- url: /
  static_dir: gwt-war

