application: marry-fuck-kill
version: staging
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /s
  static_dir: static

- url: /admin/.*
  script: admin.py
  login: admin

- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin

# Uncomment this to view stats. Also uncomment config in appengine_config.py.
#- url: /stats.*
#  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
#  login: admin

- url: /.*
  script: main.py

error_handlers:
- error_code: over_quota
  file: over_quota.html


builtins:
- remote_api: on
